[2023-09-22 21:46:41,281] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-22 21:46:41,285] INFO 127.0.0.1 - - [22/Sep/2023 21:46:41] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:46:56,256] INFO 127.0.0.1 - - [22/Sep/2023 21:46:56] "GET /agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:47:15,273] INFO 127.0.0.1 - - [22/Sep/2023 21:47:15] "POST /encontrar_consultorio HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:47:45,348] WARNING Coletando agendamentos - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_schedule_by_doctor_and_clinic.py L7   
[2023-09-22 21:47:45,350] INFO 127.0.0.1 - - [22/Sep/2023 21:47:45] "POST /encontrar_agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:47:47,834] ERROR Exception on /encontrar_agendamento [POST] - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py L1741
Traceback (most recent call last):
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask_openapi3\scaffold.py", line 127, in view_func
    response = func(**func_kwargs)
  File "D:\Workspace\MVP\consultas_medicas\rest_api\app.py", line 94, in find_a_schedule
    schedule_date = datetime.datetime.strptime(schedule_date,'%d/%m/%Y').strftime('%Y-%m-%d')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%d/%m/%Y'
[2023-09-22 21:47:47,838] INFO 127.0.0.1 - - [22/Sep/2023 21:47:47] "[35m[1mPOST /encontrar_agendamento HTTP/1.1[0m" 500 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:47:52,300] WARNING Encontrando agendamento Clinica '1', Date '2023-09-26', Time '10:00:00' - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\find_schedule.py L7   
[2023-09-22 21:47:52,303] INFO 127.0.0.1 - - [22/Sep/2023 21:47:52] "POST /encontrar_agendamento HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:48:49,389] INFO 127.0.0.1 - - [22/Sep/2023 21:48:49] "POST /agendamento HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:48:54,095] WARNING Encontrando agendamento Clinica '1', Date '2023-09-25', Time '15:00:00' - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\find_schedule.py L7   
[2023-09-22 21:48:54,097] INFO 127.0.0.1 - - [22/Sep/2023 21:48:54] "POST /encontrar_agendamento HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:49:03,326] INFO 127.0.0.1 - - [22/Sep/2023 21:49:03] "GET /agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:49:17,249] INFO 127.0.0.1 - - [22/Sep/2023 21:49:17] "GET /agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:50:36,020] INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:50:36,021] INFO [33mPress CTRL+C to quit[0m - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:50:37,843] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-22 21:50:37,848] INFO 127.0.0.1 - - [22/Sep/2023 21:50:37] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:51:33,004] INFO 127.0.0.1 - - [22/Sep/2023 21:51:33] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:51:33,245] INFO 127.0.0.1 - - [22/Sep/2023 21:51:33] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:51:33,248] INFO 127.0.0.1 - - [22/Sep/2023 21:51:33] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:51:33,264] INFO 127.0.0.1 - - [22/Sep/2023 21:51:33] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:51:33,332] INFO 127.0.0.1 - - [22/Sep/2023 21:51:33] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:51:42,315] INFO 127.0.0.1 - - [22/Sep/2023 21:51:42] "GET /agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:51:43,656] INFO 127.0.0.1 - - [22/Sep/2023 21:51:43] "GET /agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:52:45,294] WARNING Deletando agendamento Clinica '1', Date '2023-09-25', Time '15:00:00', CPF '14258613770' - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\delete_schedule.py L6   
[2023-09-22 21:52:45,299] INFO 127.0.0.1 - - [22/Sep/2023 21:52:45] "DELETE /agendamento HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:52:48,553] WARNING Deletando agendamento Clinica '1', Date '2023-09-25', Time '15:00:00', CPF '14258613770' - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\delete_schedule.py L6   
[2023-09-22 21:52:48,555] WARNING Agendamento não encontrado - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\delete_schedule.py L14  
[2023-09-22 21:52:48,556] INFO 127.0.0.1 - - [22/Sep/2023 21:52:48] "[35m[1mDELETE /agendamento HTTP/1.1[0m" 204 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:53:37,460] INFO 127.0.0.1 - - [22/Sep/2023 21:53:37] "POST /agendamento HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:53:41,134] WARNING Erro ao adicionar agendamento de Daniel para o dia '24/09/2023' '15:00', Agendamento já consta na base :/ - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\add_schedule.py L28  
[2023-09-22 21:53:41,135] INFO 127.0.0.1 - - [22/Sep/2023 21:53:41] "[31m[1mPOST /agendamento HTTP/1.1[0m" 409 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:53:52,861] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-22 21:53:52,862] INFO 127.0.0.1 - - [22/Sep/2023 21:53:52] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:53:53,527] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-22 21:53:53,529] INFO 127.0.0.1 - - [22/Sep/2023 21:53:53] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:54:08,518] INFO 127.0.0.1 - - [22/Sep/2023 21:54:08] "GET /agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:54:21,648] INFO 127.0.0.1 - - [22/Sep/2023 21:54:21] "POST /encontrar_consultorio HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:54:23,732] WARNING Coletando agendamentos - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_schedule_by_doctor_and_clinic.py L7   
[2023-09-22 21:54:23,735] INFO 127.0.0.1 - - [22/Sep/2023 21:54:23] "POST /encontrar_agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-22 21:54:37,359] WARNING Encontrando agendamento Clinica '1', Date '2023-09-26', Time '10:00:00' - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\find_schedule.py L7   
[2023-09-22 21:54:37,362] INFO 127.0.0.1 - - [22/Sep/2023 21:54:37] "POST /encontrar_agendamento HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
